#!/usr/bin/env python3

from hammer.vlsi import CLIDriver, HammerTool, HammerDriver, HammerToolHookAction

from pathlib import Path
from typing import Dict, Callable, Optional, List

from hammer.technology.sky130 import SKY130Tech

import json


def check_timing_intent(x: HammerTool) -> bool:
    x.append('check_timing_intent')
    return True

def dont_touch(x: HammerTool) -> bool:
    x.append('set_dont_touch [get_db insts -if {.base_cell.base_class == block}]')
    return True

def set_routing_layers(x: HammerTool) -> bool:
    if x.get_setting("vlsi.core.technology") == "hammer.technology.sky130" and \
       x.get_setting("vlsi.core.par_tool")   == "hammer.par.innovus" :
        x.append("""
set_db design_bottom_routing_layer 2
set_db design_top_routing_layer 6
# deprected syntax, but this used to always work
set_db route_design_bottom_routing_layer 2
        """)
    return True      

def derate_srams(x: HammerTool) -> bool:
    if x.get_setting("vlsi.core.technology") == "hammer.technology.sky130" and \
       x.get_setting("vlsi.core.par_tool")   == "hammer.par.innovus" :        
        # this is very hacky, TCL soln would be cleaner but harder to debug code
        # NOTE: this doesn't check whether it's an SRAM!!!
        floorplan_constraints = x.get_placement_constraints()
        for constraint in floorplan_constraints:
            macro_path = "/".join(constraint.path.split("/")[1:])
            # TODO: only do this if we're using .schematic.lib files
            if macro_path != "":
                x.append(f'''
set_timing_derate -cell_delay -delay_corner setup -late 3.0 [get_cells {{{macro_path}}}] 
set_timing_derate -cell_delay -delay_corner hold  -early 0.95 [get_cells {{{macro_path}}}] 
'''.strip())
    return True

def add_fillers(x: HammerTool) -> bool:
    if x.get_setting("vlsi.core.technology") == "hammer.technology.sky130" and \
       x.get_setting("vlsi.core.par_tool")   == "hammer.par.innovus" :
        x.add_fillers()  # call Innovus's add_fillers step
        # x.append("opt_design -post_route -setup -hold")
        # x.append("opt_design -post_route -hold")
    return True

def signoff_timing(x: HammerTool) -> bool:
    if x.get_setting("vlsi.core.technology") == "hammer.technology.sky130" and \
       x.get_setting("vlsi.core.par_tool")   == "hammer.par.innovus" :
        x.append('''
# setup timing
time_design -sign_off
# hold timing
time_design -sign_off -hold
''')
    return True

# def write_top_files(x: HammerTool) -> bool:
#     if x.get_setting("vlsi.core.technology") == "sky130" and \
#        x.get_setting("vlsi.core.par_tool")   == "innovus" :
#         handoff_dir = f"{x.run_dir}/handoff"
#         x.append(f'''
# mkdir -p {handoff_dir}
# # LEF file
# write_lef_abstract -stripe_pins -pg_pin_layers met5 {handoff_dir}/{x.top_module}.lef

def drc_blackbox_tdc_64(x: HammerTool) -> bool:
    if x.get_setting("vlsi.core.drc_tool")   == "hammer.drc.calibre" :
        run_file = x.drc_run_file
        with open(run_file, "a") as f:
            f.write("EXCLUDE CELL tdc_64")
    return True

def lvs_blackbox_tdc_64(x: HammerTool) -> bool:
    if x.get_setting("vlsi.core.lvs_tool")   == "hammer.lvs.calibre" :
        run_file = x.drc_run_file
        with open(run_file, "a") as f:
            f.write("LVS BOX tdc_64")
            f.write("LVS FILTER tdc_64")

def donttouch_iocells(x: HammerTool) -> bool:
    x.append('set_dont_touch [get_db insts -if {.base_cell.name == sky130_ef_io__*}] true')
    return True

def flatten_analog_driver(x: HammerTool) -> bool:
    # AnalogDriver is a kludge to get FIRRTL to understand how to connect nets
    # together, they should get dissolved
    x.append('ungroup [get_db hinsts -if {.module.name == AnalogDriver*}]')
    return True

def set_die_snap_to_mfg_grid(x: HammerTool) -> bool:
    x.append('set_db floorplan_snap_die_grid manufacturing')
    return True

def efabless_ring_io(ht: HammerTool) -> bool:
    # Copied from Harrison's version in hammer to make some adjustments:
    # - global connections removed - now handled by CPF
    # - add fixing of IO fillers
    io_file = ht.get_setting("technology.sky130.io_file")
    ht.append(f"read_io_file {io_file} -no_die_size_adjust")
    p_nets = list(map(lambda s: s.name, ht.get_independent_power_nets()))
    g_nets = list(map(lambda s: s.name, ht.get_independent_ground_nets()))
    # TODO: put only a few supply tie cells instead of replacing all 20um?
    ht.append('''
# IO fillers
#set io_fillers {sky130_ef_io__com_bus_slice_20um sky130_ef_io__com_bus_slice_10um sky130_ef_io__com_bus_slice_5um sky130_ef_io__com_bus_slice_1um}
# Use slices connecting VCCHIB<>VCCD and VSWITCH<>VDDA
set io_fillers {sky130_ef_io__connect_vcchib_vccd_and_vswitch_vddio_slice_20um sky130_ef_io__com_bus_slice_10um sky130_ef_io__com_bus_slice_5um sky130_ef_io__com_bus_slice_1um}
add_io_fillers -prefix IO_FILLER -io_ring 1 -cells $io_fillers -side top -filler_orient r0
add_io_fillers -prefix IO_FILLER -io_ring 1 -cells $io_fillers -side right -filler_orient r270
add_io_fillers -prefix IO_FILLER -io_ring 1 -cells $io_fillers -side bottom -filler_orient r180
add_io_fillers -prefix IO_FILLER -io_ring 1 -cells $io_fillers -side left -filler_orient r90
# Fix placement
set io_filler_insts [get_db insts -if {.base_cell.name == sky130_ef_io__com_bus_slice_*}]
set_db $io_filler_insts .place_status fixed
''')
    # FIXME: do something better than hardcoding CPF path
    ht.append("""
# Reload CPF to assign domains to just-placed physical-only cells
read_power_intent -cpf power_spec.cpf
commit_power_intent
""")
    ht.append(f'''
# Core ring
add_rings -follow io -layer met5 -nets {{ {p_nets[0]} {g_nets[0]} }} -offset 5 -width 13 -spacing 3
route_special -connect pad_pin -nets {{ {p_nets[0]} {g_nets[0]} }} -detailed_log
''')
    ht.append('''
# Prevent buffering on TIE_LO_ESD and TIE_HI_ESD
set_dont_touch [get_db [get_db pins -if {.name == *TIE*ESD}] .net]
''')
    return True

def route_ties(x: HammerTool) -> bool:
    x.append('''
select_net [get_db [get_db pins -if {.name == */TIE_* && .base_pin.base_cell.name == sky130_*}] .net]
route_design -selected
deselect_net *
''')
    return True

def patch_hvl_ls_lef(ht: HammerTool) -> bool:
    # Treat HVL cells as if they were hard macros to avoid needing to set them
    # up "properly" with multiple power domains

    lef_name = "sky130_fd_sc_hvl__lsbufhv2lv_1.lef"

    sky130A_path = Path(ht.get_setting('technology.sky130.sky130A'))
    source_path = sky130A_path / 'libs.ref' / 'sky130_fd_sc_hvl' / 'lef' / lef_name
    cache_path = Path(ht.technology.cache_dir) / "fd_sc_hvl__lef" / lef_name
    cache_path.parent.mkdir(exist_ok=True)

    with source_path.open("r") as sf, cache_path.open("w") as df:
        ht.logger.info(f"Patching HVL LS LEF: {source_path} -> {cache_path}")
        is_in_site_def = False
        is_in_macro_def = False
        for line in sf:
            if is_in_site_def:
                if 'END unithv' in line:
                    is_in_site_def = False
            elif not is_in_macro_def and 'SITE unithv' in line:
                is_in_site_def = True
            elif 'MACRO ' in line:
                is_in_macro_def = True
                df.write(line)
            elif 'SITE unithv' in line:
                pass
            else:
                df.write(line.replace("CLASS CORE", "CLASS BLOCK"))
    return True

def load_hv_def_routing(x: HammerTool) -> bool:
    def_path = x.get_setting("design.def.hv_routing")
    x.append(f'read_def {def_path}')
    return True

def connect_core_stripes(x: HammerTool) -> bool:
    x.append('''
route_special -connect floating_stripe -floating_stripe_target ring -nets {VDD VSS} -stripe_layer_range {met4 met5} -detailed_log
''')
    return True

class Driver(CLIDriver):
    def get_extra_synthesis_hooks(self) -> List[HammerToolHookAction]:
        return [
            HammerTool.make_post_insertion_hook("init_environment", check_timing_intent),
            HammerTool.make_post_insertion_hook("init_environment", dont_touch),
            HammerTool.make_post_insertion_hook("init_environment", donttouch_iocells),
            HammerTool.make_pre_insertion_hook("syn_generic", flatten_analog_driver),
            HammerTool.make_persistent_hook(patch_hvl_ls_lef),  # abuse persistent steps to chuck stuff in cache
        ]

    def get_extra_par_hooks(self) -> List[HammerToolHookAction]:
        return [
            # make_removal_hook will remove the specified step from the flow
            HammerTool.make_removal_hook("place_bumps"),

            HammerTool.make_pre_insertion_hook("place_opt_design", derate_srams),

            HammerTool.make_post_insertion_hook("init_design", set_routing_layers),

            # move fillers step to after opt_design
            HammerTool.make_removal_hook("add_fillers"),
            HammerTool.make_post_insertion_hook("opt_design", add_fillers),

            # add final signoff timing
            # TODO: re-add once we care about timing (DRC/LVS sane)
            # HammerTool.make_pre_insertion_hook("write_design", signoff_timing),

            # # write final files
            # HammerTool.make_post_insertion_hook("write_design", write_top_files),

            HammerTool.make_pre_insertion_hook("floorplan_design", set_die_snap_to_mfg_grid),
            HammerTool.make_post_insertion_hook("floorplan_design", efabless_ring_io),
            HammerTool.make_post_insertion_hook("efabless_ring_io", load_hv_def_routing),
            HammerTool.make_post_insertion_hook("power_straps", connect_core_stripes),

            HammerTool.make_removal_hook("place_bumps"),
            HammerTool.make_removal_hook("sky130_connect_nets"),
            HammerTool.make_removal_hook("sky130_connect_nets2"),

            HammerTool.make_persistent_hook(patch_hvl_ls_lef),  # abuse persistent steps to chuck stuff in cache
        ]
    
    def get_extra_drc_hooks(self) -> List[HammerToolHookAction]:
        return [
            HammerTool.make_post_insertion_hook("generate_drc_run_file", drc_blackbox_tdc_64)
        ]

if __name__ == '__main__':
    Driver().main()
